### ISSUE TITLE
Transformations - again

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#101]
Hi Tim,

For some reason the Dwarsberg AWS transformation on the daily soil moisture minimum is not being applied. Settings are identical to the Maximum which does work. Any ideas?

![image](https://user-images.githubusercontent.com/8395262/33878082-166e318a-df33-11e7-9f4d-fb71691893b7.png)

**Comment by TimPN-SAEON** [comment]
Servers are down, as soon as they come up I will have a look

**Comment by Abrisaeon** [comment]
Hi Tim,

A development on this I have just noticed in case it helps:

The lack of transformation application appears to only happen when one views the Observations under Import Batches. 

See here for Sneeuberg rain gauge:
![image](https://user-images.githubusercontent.com/8395262/33928551-f11cde06-dfee-11e7-9a30-9e25477181cf.png)


When viewed in the Data Query Display, it looks like the transformation did actually get applied.

![image](https://user-images.githubusercontent.com/8395262/33928600-16e2b976-dfef-11e7-819a-4a67d4f3be22.png)

**Comment by Abrisaeon** [comment]
The same however doesn't apply for Dwarsberg daily soil moisture. Here the transformation applied to the Maximum works but the Minimum does not. I've tried any number of different combinations of rankings with and without start & end dates. I did manage to switch the problem to Max instead of Min at one stage (to do with rankings I think) but reversed it again.

![image](https://user-images.githubusercontent.com/8395262/33932783-9944b218-dffc-11e7-9c0c-8f14e0ed95e9.png)

**Comment by TimPN-SAEON** [comment]
Hi Abri

For the Sneeuberg I see that the transform has been made for the tips, but to 0.254 instead of 0.2. Any idea why 0.254?

![image](https://user-images.githubusercontent.com/29254126/33939211-eeddc4a6-e012-11e7-8c60-cf3bf4a350a2.png)

**Comment by Abrisaeon** [comment]
Hi Tim,

That's because it's a new rain gauge that measures rainfall in 0.254 mm increments

**Comment by TimPN-SAEON** [comment]
Ok, so are you now happy with Sneeuberg?

**Comment by Abrisaeon** [comment]
Yes, it looks fine

**Comment by Abrisaeon** [comment]
Hi again Tim,

Related to the same topic, I've added a new Texas rain gauge sensor to each of the 5B, 21B, 25B and 26B stations in Jonkershoek. I've configured them identically with Transformation end dates for the old sensors ending on 26 October 2017 (the last data for the day varies between morning and early afternoon depending on the site). Transformation start dates for the new sensors start on the 26th. I've got the transformation rankings identical as well apart from a couple of the sources which have an additional QC transformation as a third add on. Now for the weird part....

Two of the sensors' data load with the correct start and end times. The other two create fake data to complete the old sensor's day and start the new sensor's record from the 27th at 00:00

![image](https://user-images.githubusercontent.com/8395262/33939381-a2b72d28-e013-11e7-9915-ea7fdad5eb97.png)

**Comment by TimPN-SAEON** [comment]
You need to filter on Phenomenon "Rainfall", RawValue > 0 to see the tips in Import Batches.

Now to Dwasberg...

**Comment by Abrisaeon** [comment]
More transformation weirdness...

Untransformed Raw Values and transformed Data Values in the Observations under Import Batches - perfect!

![image](https://user-images.githubusercontent.com/8395262/33943253-41956920-e021-11e7-9e0a-d99d1fb8f9aa.png)

Same data viewed through the Query Display...

![image](https://user-images.githubusercontent.com/8395262/33943299-69d86036-e021-11e7-9293-20349f38861f.png)

**Comment by Abrisaeon** [comment]
Hospital Bend Block A bottom daily has a very similar transformation problem as Dwarsberg -  a Minimum that transforms and a Maximum that doesn't...

![image](https://user-images.githubusercontent.com/8395262/33943808-c887cac6-e022-11e7-85b0-72ba899b748a.png)

**Comment by TimPN-SAEON** [comment]
Hi Abri

Still no idea why. I did notice that for some reason the sensors have a schema which in this case is not the right way to set sensors up.

Will do more investigation and get back to you.

**Comment by Abrisaeon** [comment]
Yes, that's how Victoria set them up back in the day because of the fact that there are several soil moisture sensors measuring the same phenomena and offering. It was a very complicated exercise that I still don't quite understand the reason for. 

Either way, the database accepted a few years worth of data and performed the transformations 100% up until a few months ago. I've subsequently deleted all the daily data which did not have transformations applied correctly. So you can see where the error started. 

The problem seems to be when one does a transformation on the same phenomenon from the same data source (even if it is two different sensors each with its own unique offering). I'm encountering the exact same problem at Hospital Bend...well, almost...in the Hospital Bend case it is reversed.

**Comment by TimPN-SAEON** [comment]
Ok, will delve deeper

**Comment by TimPN-SAEON** [comment]
Ok, I have found the problem. Please try again and let me know if its fixed....

**Comment by Abrisaeon** [comment]
I've tested it for Dwarsberg and it looks like the problem has been solved. Was it something I was doing wrong?

**Comment by TimPN-SAEON** [comment]
Nope, was the schema on sensor which means the file is processed a number of times. There was a glitch in that after the each processing the values were reset to the raw value. So it was order dependent on which transformations didn't get overwritten.

We don't have that problem with the schema on the datasource.
