### ISSUE TITLE
Data source - sensor link drop down uncoordinated? 

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#13]
New Data Source does not immediately appear in Sensor Detail "Data Source" drop down list when attempting to link a new sensor to a new data source. It does appear in the list if one logs out and logs back in.

**Comment by TimPN-SAEON** [comment]
Tabs are not linked, so changes in one do not propagate to the other. Closing and reopening the tab should load the changes. I am looking for a better way to handle this problem.
