### ISSUE TITLE
Choosing new offerings for a phenomenon

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#146]
Hi Tim,

In the process of trying to test the new expression transformation I'm trying to use some actual current stream height data. We previously (up to about Sept 2017) collected this as an average offering (two half hourly values averaged and stored on the hour), but we do now need to add "actual" as an offering. 

My problem is it's impossible to select "actual" as an offering because "Available offerings" table is filled with Elwandle's "depth at minute interval" offerings with no way to navigate between pages of the table. Filtering by "Actual" doesn't do anything.

Could you advise how I should go about this?

**Comment by Abrisaeon** [comment]
Hi Tim,

If you select the "Streamflow height" phenomenon and click to "add offering" you can see what I mean. 

![offering](https://user-images.githubusercontent.com/8395262/49717240-10474900-fc5f-11e8-867d-1c0dc1846ee8.JPG)

**Comment by TimPN-SAEON** [comment]
Ok grid is now sorted and filtering is now working

**Comment by Abrisaeon** [comment]
Thanks Tim,

That problem has now been fixed. I'll open another ticket for the other issue I was trying to describe in my last email
