### ISSUE TITLE
Expression transformation requires transformation of phenomena

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#147]
Hi Tim,

As mentioned in my email (quoted just to refresh your memory): 
"I've noticed that the old "ratings table" transformation used "streamflow volume" as an input phenomenon and just changes the unit of measure from "meter" to "cubic meters per second". While this may produce acceptable results, it isn't technically correct or intuitive. An improvement would be to use "Streamflow height" (a phenomenon that already exists) in meters as an input and transform this into "streamflow volume" as an output phenomenon with an "actual" offering."

We've addressed the issue of adding "actual"  as an offering to any phenomenon by being able to sort the list of offerings.

The Expression transformation however (like the ratings table transformation before it) can't transform one phenomenon into another (yet). I think you'd agree that stream height (or what the database calls streamflow height) and flow volume (streamflow volume) are two different phenomena. 

Currently one can input one offering and output another offering within a specific phenomenon. What we need to do is input one phenomenon and output another phenomenon altogether.

**Comment by TimPN-SAEON** [comment]
Hi Abri

I agree its not logical at the moment. Will let you know once I have added the new Phenomenon to the form

Regards

Tim

**Comment by TimPN-SAEON** [comment]
Hi Abri

There is a new version that allows you to specify a new Phenomenon in the transformation. You are going to have to create a new dataschema that has StreamFlowHeight instead of StreamFlowVolume for the column.

Please test it and let me know what happens.

Regards

Tim

**Comment by Abrisaeon** [comment]
Thanks Tim. Busy checking it out now.
