### ISSUE TITLE
Transformation detail validate?

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#149]
Hi Tim,

The transformation detail tab you set up looks like it has everything we need now. I've populated it and it has a green tick mark at the bottom left. I clicked on "validate" out of curiosity and I get a pop up message that says "observationsadmin.saeon.ac.za says Invalid". It lets me save it though, so I have. Could you confirm the reason why it's invalid?

I'll go ahead and test a small upload anyway.

Thanks

**Comment by TimPN-SAEON** [comment]
Hi Abri

That's just for me testing, forgot to remove it. Will do when I publish the
datasource filter fix.

Regards

Tim

Tim Parker-Nance
Senior Developer (Coastal)
Elwandle Coastal Node <http://elwandle.saeon.ac.za>
South African Environmental Observation Network (SAEON) of the National
Research Foundation (NRF)
Office 25, A Block, Ocean Sciences Campus, Nelson Mandela University, Gomery
Avenue <https://www.google.co.za/maps/@-34.0010891,25.6673859>,
Summerstrand, Port Elizabeth
Tel: +27 41 504 4946 Cell: +27 72 141 7953
timpn@saeon.ac.za
www.saeon.ac.za

SAEON is a comprehensive, sustained, coordinated and responsive South
African environmental observation network that delivers long-term reliable
data for scientific research and informs decision-making for a knowledge
society and improved quality of life.

Hot off the press: Download the 2017 SAEON ANNUAL REPORT
<http://bit.ly/2v78RJ2>

**Comment by Abrisaeon** [comment]
Cool
