### ISSUE TITLE
Date column format new option - data schemas

### ISSUE THREAD

**Issue by briglm** [SAEONData/SAEON-Observations-Database#152]
It would be helfpul to have a format option that only contains MM/YYY. For example, monthly rainfall data collected from farmers don't usually have a day attached to it. It will prevent confusion for people putting in arbitrary days to meet formatting requirements.

**Comment by TimPN-SAEON** [comment]
The dropdown is only to give you a hint on how the format works. You can type your own format into the textbox of the dropdown. If the format validates you will be able to save the column.
