### ISSUE TITLE
Data schemas - currently unable to have more than one offering column

### ISSUE THREAD

**Issue by briglm** [SAEONData/SAEON-Observations-Database#154]
Similar issue to the "multiple columns that can be ignored" (which has now been fixed), I cannot seem to add more than one offering column. Other data schemas seem to have more than one, so this is a new bug.
Thanks

**Comment by TimPN-SAEON** [comment]
Ok, I have 'relaxed' the check. Now it only moans if the offering and unit of measure already exist in the schema.
