### ISSUE TITLE
Inventory not downloadable?

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#158]
Hi Tim,

Following today's meeting about standard operating procedures with Gregor, Sue, Shaun & Juliet, I've been tasked to get some details on our data holdings to the group so we can work out where SOPs exist and where not. 

I've downloaded the phenomena and offerings lists as csv files. I also wanted to download the inventory but the download buttons don't seem to be active. Could you have a look at these?

Then, while on the topic of phenomena and offerings, is there a way one can extract the two together so its possible to see which offerings are available for each phenomenon?

Thanks

**Comment by TimPN-SAEON** [comment]
Hi Abri

The Inventory is now downloadable.

Attached is the Phenomenon Offering Unit summary. Count is the number of sensors.

Regards

Tim
[PhenomenonOfferingUnit.xlsx](https://github.com/SAEONData/SAEON-Observations-Database/files/3080395/PhenomenonOfferingUnit.xlsx)

**Comment by Abrisaeon** [comment]
Great! Thanks. Just curious, is there a way a mere mortal could download that summary from the ObsDB and I'm just too incompetent to do it? Or did you extract it in some other way?

**Comment by TimPN-SAEON** [comment]
Hi Abri

I had to extract it from the database. Will raise an issue and add it to the new query site.
