### ISSUE TITLE
Inventory not downloading

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#181]
Hi Tim,

I'm trying to download the inventory filtered by JNHK (site code). It won't download a .csv or .xlsx file.

Abri

**Comment by TimPN-SAEON** [comment]
Busy looking into this. Will get back to you shortly

**Comment by TimPN-SAEON** [comment]
Ok, I have fixed this. Struggling to publish to the server. I Will let you know when it's ready.
