### ISSUE TITLE
Odd error message 

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#189]
Hi Tim,

I get the error below when trying to upload hourly weather data for the Engelsmanskloof AWS. Any idea what it means?

Abri

![obsdb error](https://user-images.githubusercontent.com/8395262/123946441-820f4b80-d99f-11eb-9895-561e42ff67bb.PNG)

**Comment by NimbusServices** [comment]
Let me have a look and get back to you

**Comment by NimbusServices** [comment]
Hi Abri

This was a weird one! If you open the .dat file, line 1889 & 1890 are duplicates with some different values.
2021-05-05 20:00:00,8357,1019.197,0,9.1,95.7,0.009,0.484,294.9,5.745,11.55,2.285
2021-05-05 20:00:00,8358,1019.249,0,8.45,94.8,0.005,0.306,207.6,7.761,11.06,0.513

No idea how that was possible. There was an issue in my duplicate check that is now fixed. If you do the import the error goes away but you do get duplicates in the log.

By the way, I have been using Visual Studio Code to view CSVs, which works much better than Excel https://code.visualstudio.com/

Regards

Tim
