### ISSUE TITLE
Transformations not working correctly

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#201]
Hi Tim,

I've just discovered this rather alarming issue. The transformation appears to be correctly set up but it converts positive stream flow values into random, sometimes even negative values. I haven't looked for the issue very widely. Just at Bosboukloof weir, where it seems to affect the actual half hourly stream flow.
See below:

![transformation](https://user-images.githubusercontent.com/8395262/135095614-0aa2e211-0996-498f-8ee4-b2536cfb07b6.PNG)

Any idea what could cause this?

**Comment by TimPN-SAEON** [comment]
Hi Abri

No idea why, I haven't worked on the Admin site for a while. Will download the backup from the server (takes forever) and have a look and get back to you

**Comment by TimPN-SAEON** [comment]
I have checked the values in my Transformation Calculator. The values do come out as negative. So there is an error in either the parameters or the formula.
