### ISSUE TITLE
Link Instrument error

### ISSUE THREAD

**Issue by MargMarie** [SAEONData/SAEON-Observations-Database#45]
I received an error message when linking the instrument in a new station Belvedere Farm.  The instrument is now linked, but a link has also been made other places"
Site - a link has been made under organisations
Stations - a link has been made under organisations
Instruments - a link has been made under organisations

![belvedere link instrument error](https://cloud.githubusercontent.com/assets/22613363/21305902/c9e319c8-c5d6-11e6-9ec0-a668a3a57ee4.jpg)

**Comment by TimPN-SAEON** [comment]
Link saving now checks for duplicates and prompts with a more useful error message.
