### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#55]
Hi Tim,

I've been meaning to ask you about this for a while. The inventory page on the database has been out of order for quite some time (screenshot below). Are you doing work on improving it? Will it be replaced with something else? Or is it simply something that went bad during the merge?

I'm asking because some of our colleagues at the Grasslands Node want to use the inventory function.

![image](https://cloud.githubusercontent.com/assets/8395262/22732711/dd54aa5a-edf7-11e6-8660-8534251a31a2.png)

Abri

**Comment by TimPN-SAEON** [comment]
Inventory now displays as per previous version
