### ISSUE TITLE
Data takes a long time to upload and uploads time out without loading

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#62]
Hi Tim,

I've run into this issue repeatedly, on Monday and again Thursday. I'm trying to upload data to the Langrivier 600 fog station at Jonkershoek after editing the schema and creating new sensors. I've uploaded some of the backlog (a file that did not include the additional sensors) and am now trying to upload a file that does. 

I've tried with the full version of the file (more than a year's worth of hourly data) and with a shortened version due to the fact that I get this error message:

![image](https://cloud.githubusercontent.com/assets/8395262/23843520/1b2c5800-07c5-11e7-9876-37688a77c88b.png)

I did manage to test load a shortened version of this file on Friday but it took surprisingly long.

**Comment by TimPN-SAEON** [comment]
Rewrite of import fixed this problem
