### ISSUE TITLE
All data does not display in query

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#85]
Hi Tim,

I've discovered an odd problem. Hopefully it isn't me doing something silly. Data that I've loaded for Sneeukophut rain gauge (Cederberg) starts at 2 December 2015. However when I try to view data (in order to download) in the query display, it doesn't give me data going that far back (only starts at 00:00 1 Jan 2016).

As far as I can see the start dates of everything is set to 2 December 2015 (which explains why it imports successfully). What am I missing?

![image](https://user-images.githubusercontent.com/8395262/28465500-41cd936e-6e29-11e7-997c-e412108e0ded.png)

![image](https://user-images.githubusercontent.com/8395262/28465546-7488927c-6e29-11e7-88ad-3483d4e1ed1d.png)

**Comment by TimPN-SAEON** [comment]
Tracked it down. On the Data Source, Roles the Admin role only starts 1 Jan 2016. I would suggest leaving the start date and end date null unless there is a requirement to limit the role to specific dates.
