### ISSUE TITLE
Observations tab under Data Views

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#95]
Hi Tim, 

I'm doing a bit more exploring on the ObsDB than I normally would in preparation for the training. 

What is the point of the Observations tab under the Data Views section?

![image](https://user-images.githubusercontent.com/8395262/32827127-c05ecfe2-c9f3-11e7-8797-918d7f97a23a.png)

Is it supposed to be a list of every single observation on the Database? The information (at least on the first page) doesn't seem to be particularly useful or accurate

I notice it and the Inventory pages are dreadfully slow.

**Comment by TimPN-SAEON** [comment]
Hi Abri

To be honest I have no idea, it pre dates me. I will see what the code is
doing and get back to you.

Tim

Tim Parker-Nance
Senior Developer (Coastal)
Elwandle Coastal Node
South African Environmental Observation Network (SAEON)
Room A27, NMU Ocean Sciences Campus, 4 Gomery Avenue, Port Elizabeth
Tel: +27 41 504 4750 Cell: +27 72 141 7953
timpn@saeon.ac.za
www.saeon.ac.za

**Comment by TimPN-SAEON** [comment]
Ok, I see no point of this as the new Query site will give proper access to the data. So I suggest I remove it.

**Comment by Abrisaeon** [comment]
Makes sense. No point in duplicating.
