### ISSUE TITLE
Station geo location

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#96]
Hi Tim,

I see there are fields where one can/should enter geo location details on the Station link tab under Instruments.  What is the purpose of this if the Station and Instrument both have (optional) fields for geo locations already?

![station geo](https://user-images.githubusercontent.com/8395262/33012474-b07ca0b4-cde9-11e7-8f74-c962f73109d3.JPG)

**Comment by TimPN-SAEON** [comment]
Its to handle the marine equipment. Typically the station will have a general position, the instrument not cause they move between stations. But each deployment of the instrument will, so the link has the position.

For the terrestrial equipment the station will have a position, but you might have a number of instruments close by but at different positions. In this case the instrument will have to position.
