### ISSUE TITLE
Offering options - cluttering by "Depth" 

### ISSUE THREAD

**Issue by Abrisaeon** [SAEONData/SAEON-Observations-Database#97]
Hi Tim,

Have you seen what happens when one is in the Phenomenon section and you try to link an Offering to a specific phenomenon? 

A list of Offerings appear that is filled with a million and one of (I ssume, Elwandle's ) depth offerings. The offerings window that opens doesn't have pages that one can navigate to get out of the "D" section (that's completely cluttered with "Depth") and one can't filter the columns either.

![offering options](https://user-images.githubusercontent.com/8395262/33012966-121828d8-cdeb-11e7-8be2-d39bd8613e3c.JPG)

**Comment by TimPN-SAEON** [comment]
I will see if I can get a filter going to help with this.

Once the depth issue is resolved the 3000 odd depth phenomena will be removed.

**Comment by TimPN-SAEON** [comment]
Depth cleanup has completed
